#!/bin/bash

echo ""
echo "System Report- Generated By $(whoami) on $(date)"

echo "SYSTEM INFO:"
echo "-------------------"
echo "Hostname: $(hostname)"  #Get system hostname
echo "OS: $(cat /etc/issue )" #Get OS information
echo "UPTIME: $(uptime)" #Display Sytem uptime

echo "HARDWARE: "
echo "----------------------"
echo "CPU: $(lscpu | grep 'Model name')" #Get CPU model
echo "RAM: $(free -h | grep Mem | awk '/^Mem:/ {print $2}' )" #Get Total RAM
echo "DISKS: $(lsblk -ndo NAME,SIZE,MODEL )" #List all devices with name , size and model
echo "VIDEO: $(lspci | grep VGA)" #Get graphics card information

echo "NETWORK INFORMATION:"
echo "------------------------"
echo "FQDN: $(hostname -f)" #Get Domian name
echo "HOST ADDRESS: $(hostname -I | awk '{print $1 }')" #Get IP address
echo "GATEWAY ADDRESS: $(ip route | grep default | awk '{print $3}')" #Get default gateway
echo "DNS: $(grep nameserver /etc/resolv.conf | head -1 | awk '{print $2}')" #Get primary DNS Server

echo "SYSTEM STATUS:"
echo "---------------------------------------------------------"
echo "USERS LOGGED IN: $(who | awk '{print $1}' | sort -u  )" #list of logged-in users
echo "DISK_SPACE: $(df -h / | awk 'NR==2 {print $4}')" # Available space 
echo "PROCESS COUNT: $(ps -e | wc -l)" # Count total running processes
echo "LOAD AVERAGE: $(cat /proc/loadavg )" #System Load average
echo "LISTENING NETWORK PORTS: $(ss -tuln | awk '{print $5}'| sort -u )" #list of unique listening ports
echo "UFW STATUS: $(sudo ufw status | grep -q active && echo "enabled" || echo "disabled")" # Check UFW firewall Status


