#!/bin/bash

echo ""
echo "System Report- Generated By $(whoami) on $(date)"
echo "-----------------------------------------------"

echo "SYSTEM INFO:"
echo "Hostname: $(hostname)"
echo "OS: $(cat /etc/issue )"
echo "UPTIME: $(uptime)"

echo "HARDWARE: "
echo "-------------------------------------------------"
echo "CPU: $(lscpu | grep 'Model name')"
echo "RAM: $(free -h | grep Mem | awk '/^Mem:/ {print $2}' )"
echo "DISKS: $(lsblk -ndo NAME,SIZE,MODEL )"
echo "VIDEO: $(lspci | grep VGA)"

echo ""
echo "NETWORK INFORMATION:"
echo "----------------------------------------------------"
echo "FQDN: $(hostname -f)"
echo "HOST ADDRESS: $(hostname -I | awk '{print $1 }')"
echo "GATEWAY ADDRESS: $(ip route | grep default | awk '{print $3}')"
echo "DNS: $(grep nameserver /etc/resolv.conf | head -1 | awk '{print $2}')"
echo ""

echo "SYSTEM STATUS:"
echo "---------------------------------------------------------"
echo "USERS: $(who | awk '{print $1}' | sort -u  )"
echo "DISK_SPACE: $(df -h / | awk 'NR==2 {print $4}')"
echo "PROCESS COUNT: $(ps -e | wc -l)"
echo "LOAD AVERAGE: $(cat /proc/loadavg )"
echo "LISTENING NETWORK PORTS: $(ss -tuln | awk '{print $5}'| sort -u )"
echo "UFW STATUS: $(sudo ufw status | grep -q active && echo "enabled" || echo "disabled")"

echo "THIS IS THE END OF THE SYSTEM REPORT "
